# Generated by Django 3.2.13 on 2022-06-20 19:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название места')),
                ('place_id', models.CharField(blank=True, max_length=200, verbose_name='Place id места')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Короткое описание')),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название изображения')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('my_order', models.PositiveIntegerField()),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
