# Generated by Django 3.2.13 on 2022-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageplace',
            name='my_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
