# Generated by Django 3.2.14 on 2022-08-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_place_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageplace',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='imageplace',
            old_name='my_order',
            new_name='order',
        ),
    ]
